In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statistics

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/hana1/project1/data/train_outlier_drop2.csv', index_col = 0)
df_test = pd.read_csv('/content/drive/MyDrive/hana1/project1/data/test_outlier_drpo2.csv', index_col = 0) # 20*28

In [ ]:
df_train.head()

Month   Age  Occupation  Annual_Income  Monthly_Inhand_Salary  \
3      4  23.0          12       19114.12            1824.843333   
5      6  23.0          12       19114.12            1824.843333   
6      7  23.0          12       19114.12            1824.843333   
7      8  23.0          12       19114.12            1824.843333   
8      1  28.0          13       34847.84            3037.986667   

   Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  \
3                3.0              4.0            3.0          4.0   
5                3.0              4.0            3.0          4.0   
6                3.0              4.0            3.0          4.0   
7                3.0              4.0            3.0          4.0   
8                2.0              4.0            6.0          1.0   

   Delay_from_due_date  ...  Credit_Mix  Outstanding_Debt  \
3                  5.0  ...           1            809.98   
5                  8.0  ...           1            809.98   
6                  3.0  ...           1            809.98   
7                  3.0  ...           1            809.98   
8                  3.0  ...           1            605.03   

   Credit_Utilization_Ratio  Credit_History_Age  Payment_of_Min_Amount  \
3                 31.377862               268.0                      0   
5                 27.262259               270.0                      0   
6                 22.537593               271.0                      0   
7                 23.933795               270.0                      0   
8                 24.464031               319.0                      0   

   Total_EMI_per_month  Amount_invested_monthly  Payment_Behaviour  \
3            49.574949               199.458074                  5   
5            49.574949                62.430172                  1   
6            49.574949               178.344067                  5   
7            49.574949                24.785217                  1   
8            18.816215               104.291825                  5   

   Monthly_Balance  Credit_Score  
3       223.451310             0  
5       340.479212             0  
6       244.565317             0  
7       358.124168             2  
8       470.690627             2  

[5 rows x 23 columns]

In [ ]:
df_test.head()

Month   Age  Occupation  Annual_Income  Monthly_Inhand_Salary  \
0      9  23.0          12       19114.12            1824.843333   
1     10  24.0          12       19114.12            1824.843333   
2     11  24.0          12       19114.12            1824.843333   
3     12  24.0          12       19114.12            1824.843333   
4      9  28.0          13       34847.84            3037.986667   

   Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  \
0                3.0              4.0            3.0          4.0   
1                3.0              4.0            3.0          4.0   
2                3.0              4.0            3.0          4.0   
3                3.0              4.0            3.0          4.0   
4                2.0              4.0            6.0          1.0   

   Delay_from_due_date  ...  Num_Credit_Inquiries  Credit_Mix  \
0                  3.0  ...                2022.0           1   
1                  3.0  ...                   4.0           1   
2                 -1.0  ...                   4.0           1   
3                  4.0  ...                   4.0           1   
4                  3.0  ...                   5.0           1   

   Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
0            809.98                 35.030402               273.0   
1            809.98                 33.053114               274.0   
2            809.98                 33.811894               274.0   
3            809.98                 32.430559               276.0   
4            605.03                 25.926822               327.0   

   Payment_of_Min_Amount  Total_EMI_per_month  Amount_invested_monthly  \
0                      0            49.574949               236.642682   
1                      0            49.574949                21.465380   
2                      0            49.574949               148.233938   
3                      0            49.574949                39.082511   
4                      0            18.816215                39.684018   

   Payment_Behaviour  Monthly_Balance  
0                  5       186.266702  
1                  1       361.444004  
2                  4       264.675446  
3                  1       343.826873  
4                  0       485.298434  

[5 rows x 22 columns]

In [ ]:
# train 데이터와 test 데이터로 분할

#Spli Input & Output Data
X_train = df_train.drop('Credit_Score',axis=1)
y_train = df_train['Credit_Score']
X_test = df_test
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)

(50503, 22)
(50503,)
(24683, 22)


# model building

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score,classification_report,confusion_matrix

# Extra Tree

#### 데이터 분할

In [ ]:
# Split Data 8:2
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42,stratify=y_train)
print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(40402, 22)
(10101, 22)
(40402,)
(10101,)


#### 모델 훈련 & 교차검증

In [ ]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs = -1, random_state=42)
scores = cross_validate(et, X_train, y_train, return_train_score=True,
                        n_jobs = -1, cv = 5)
print("5-fold : ", scores['test_score'])

5-fold :  [0.80064348 0.79767356 0.80569307 0.80470297 0.80247525]


In [ ]:
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

1.0 0.8022376654198027


#### 성능평가

In [ ]:
et.fit(X_train, y_train)

ExtraTreesClassifier(n_jobs=-1, random_state=42)

In [ ]:
y_train_pred = et.predict(X_train)
y_val_pred = et.predict(X_val)
print(y_train_pred[:5])
print(y_train.values[:5])
print(y_val_pred[:5])
print(y_val.values[:5])

[2 2 0 2 2]
[2 2 0 2 2]
[2 2 2 1 1]
[2 2 2 1 1]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_train, y_train_pred))
print(classification_report(y_val, y_val_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7445
           1       1.00      1.00      1.00     10597
           2       1.00      1.00      1.00     22360

    accuracy                           1.00     40402
   macro avg       1.00      1.00      1.00     40402
weighted avg       1.00      1.00      1.00     40402

              precision    recall  f1-score   support

           0       0.77      0.76      0.77      1861
           1       0.81      0.80      0.80      2650
           2       0.83      0.84      0.84      5590

    accuracy                           0.82     10101
   macro avg       0.80      0.80      0.80     10101
weighted avg       0.82      0.82      0.82     10101



In [ ]:
y_pred = et.predict(X_test)
y_pred   # standard=2 빼오기

array([0, 2, 2, ..., 2, 2, 1])

# standard 빼오기

In [ ]:
df_test['Credit_Score'] = y_pred

In [ ]:
df_test

Month   Age  Occupation  Annual_Income  Monthly_Inhand_Salary  \
0          9  23.0          12       19114.12            1824.843333   
1         10  24.0          12       19114.12            1824.843333   
2         11  24.0          12       19114.12            1824.843333   
3         12  24.0          12       19114.12            1824.843333   
4          9  28.0          13       34847.84            3037.986667   
...      ...   ...         ...            ...                    ...   
49992      9  29.0           1       20002.88            1929.906667   
49993     10  29.0           1       20002.88            1929.906667   
49994     11  29.0           1       20002.88            1929.906667   
49997     10  25.0           9       39628.99            3359.415833   
49998     11  25.0           9       39628.99            3359.415833   

       Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  \
0                    3.0              4.0            3.0          4.0   
1                    3.0              4.0            3.0          4.0   
2                    3.0              4.0            3.0          4.0   
3                    3.0              4.0            3.0          4.0   
4                    2.0              4.0            6.0          1.0   
...                  ...              ...            ...          ...   
49992               10.0              8.0           29.0          5.0   
49993               10.0              8.0           29.0          5.0   
49994               10.0              8.0           29.0          5.0   
49997                4.0              6.0            7.0          2.0   
49998                4.0              6.0            7.0          2.0   

       Delay_from_due_date  ...  Credit_Mix  Outstanding_Debt  \
0                      3.0  ...           1            809.98   
1                      3.0  ...           1            809.98   
2                     -1.0  ...           1            809.98   
3                      4.0  ...           1            809.98   
4                      3.0  ...           1            605.03   
...                    ...  ...         ...               ...   
49992                 33.0  ...           0           3571.70   
49993                 33.0  ...           0           3571.70   
49994                 33.0  ...           0           3571.70   
49997                 23.0  ...           1            502.38   
49998                 21.0  ...           1            502.38   

       Credit_Utilization_Ratio  Credit_History_Age  Payment_of_Min_Amount  \
0                     35.030402               273.0                      0   
1                     33.053114               274.0                      0   
2                     33.811894               274.0                      0   
3                     32.430559               276.0                      0   
4                     25.926822               327.0                      0   
...                         ...                 ...                    ...   
49992                 32.391288                76.0                      1   
49993                 37.528511                77.0                      1   
49994                 27.027812                78.0                      1   
49997                 36.858542               384.0                      0   
49998                 39.139840               385.0                      0   

       Total_EMI_per_month  Amount_invested_monthly  Payment_Behaviour  \
0                49.574949               236.642682                  5   
1                49.574949                21.465380                  1   
2                49.574949               148.233938                  4   
3                49.574949                39.082511                  1   
4                18.816215                39.684018                  0   
...                    ...                      ...                ...   
49992            60.964772   

In [ ]:
df_test['Credit_Score'].value_counts()

2    14007
1     6393
0     4283
Name: Credit_Score, dtype: int64

In [ ]:
df_standard = df_test[df_test['Credit_Score'] == 2]
df_standard

Month   Age  Occupation  Annual_Income  Monthly_Inhand_Salary  \
1         10  24.0          12       19114.12            1824.843333   
2         11  24.0          12       19114.12            1824.843333   
3         12  24.0          12       19114.12            1824.843333   
8          9  35.0           4      143162.64           12187.220000   
9         10  35.0           4      143162.64           12187.220000   
...      ...   ...         ...            ...                    ...   
49975     12  33.0          10       59146.36            4908.863333   
49992      9  29.0           1       20002.88            1929.906667   
49993     10  29.0           1       20002.88            1929.906667   
49994     11  29.0           1       20002.88            1929.906667   
49997     10  25.0           9       39628.99            3359.415833   

       Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  \
1                    3.0              4.0            3.0          4.0   
2                    3.0              4.0            3.0          4.0   
3                    3.0              4.0            3.0          4.0   
8                    1.0              5.0            8.0          3.0   
9                    1.0              5.0            8.0          3.0   
...                  ...              ...            ...          ...   
49975                3.0              6.0            6.0          1.0   
49992               10.0              8.0           29.0          5.0   
49993               10.0              8.0           29.0          5.0   
49994               10.0              8.0           29.0          5.0   
49997                4.0              6.0            7.0          2.0   

       Delay_from_due_date  ...  Credit_Mix  Outstanding_Debt  \
1                      3.0  ...           1            809.98   
2                     -1.0  ...           1            809.98   
3                      4.0  ...           1            809.98   
8                      8.0  ...           1           1303.01   
9                      6.0  ...           1           1303.01   
...                    ...  ...         ...               ...   
49975                  8.0  ...           1            418.03   
49992                 33.0  ...           0           3571.70   
49993                 33.0  ...           0           3571.70   
49994                 33.0  ...           0           3571.70   
49997                 23.0  ...           1            502.38   

       Credit_Utilization_Ratio  Credit_History_Age  Payment_of_Min_Amount  \
1                     33.053114               274.0                      0   
2                     33.811894               274.0                      0   
3                     32.430559               276.0                      0   
8                     35.229707               221.0                      0   
9                     35.685836               222.0                      0   
...                         ...                 ...                    ...   
49975                 26.830861               252.0                      0   
49992                 32.391288                76.0                      1   
49993                 37.528511                77.0                      1   
49994                 27.027812                78.0                      1   
49997                 36.858542               384.0                      0   

       Total_EMI_per_month  Amount_invested_monthly  Payment_Behaviour  \
1                49.574949                21.465380                  1   
2                49.574949               148.233938                  4   
3                49.574949                39.082511                  1   
8               246.992319               397.503654                  4   
9               246.992319               453.615131                  3   
...                    ...                      ...                ...   
49975            26.778419   

In [ ]:
#drop_standard_test = df_standard.to_csv('C:\\Users\\User\\Desktop\\프로젝트1(신용평가)\\Data\\drop_standard_test.csv')